title: Víctor Collado's Homepage
page-top-title: Víctor Collado
top-section-bg-text: Computer Science
home-subtitle: Víctor Collado&ensp;|&ensp;
copyright-text: '&copy; Víctor Collado 2023-2025. All Rights Reserved.'
