title: Víctor Collado's Homepage
page-top-title: Víctor Collado Fernández
top-section-bg-text: Mathematics | Data Science
home-subtitle: Víctor Collado Fernández&ensp
copyright-text: '&copy; Víctor Collado 2023-2025. All Rights Reserved.'
